# Default values for service1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 851725552187.dkr.ecr.eu-north-1.amazonaws.com/service2
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: [name: regcred]
nameOverride: ""
fullnameOverride: ""

env:
  MONGODB_URL: mongodb

service:
  type: LoadBalancer
  port: 80
  targetPort: 3001
  protocol: TCP

rresources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
    
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
