apiVersion: v1
kind: Service
metadata:
  name: {{ include "service1.fullname" . }}
  labels:
    {{- include "service1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{$serviceName := print  .Values.service.protocol "-" .Values.service.targetPort }}
  selector:
    {{- include "service1.selectorLabels" . | nindent 4 }}
