apiVersion: v1
kind: Service
metadata:
  labels:
    app: service2
  name: service2
spec:
  ports:
  - name: 3001-3001
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: service1
  type: ClusterIP
