name: Docker Build svc1 & svc2

on:
  push:
    branches: [ "master","dev" ]
  pull_request:
    branches: [ "master","dev" ]

env:
  ecr_url: ${{ vars.AWS_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

jobs:

  build-service1:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v3
    - name: get ECR creds
      run: aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ecr_url }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
    - name: Build the SERVICE1 Docker image
      run: docker build packages/service1/. -t service1
    - name: tag specific version for SERVICE1
      run: docker tag service1:latest ${{ env.ecr_url }}/service1:$(date +%s)
    - name: tag as latest SERVICE1
      run: docker tag service1:latest ${{ env.ecr_url }}/service1:latest
    - name: push SERVICE1 $(date +%s)
      run: docker push ${{ env.ecr_url }}/service1:$(date +%s)
    - name: push SERVICE1 latest
      run: docker push ${{ env.ecr_url }}/service1:latest
      
  build-service2:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v3
    - name: get ECR creds
      run: aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ecr_url }}
      env:  
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}      
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }} 
        AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }} 
    - name: Build the SERVICE2 Docker image
      run: docker build packages/service2/. -t service2
    - name: tag specific version for SERVICE2
      run: docker tag service2:latest ${{ env.ecr_url }}/service2:$(date +%s)
    - name: tag as latest SERVICE2
      run: docker tag service2:latest ${{ env.ecr_url }}/service2:latest
    - name: push SERVICE2 $(date +%s)
      run: docker push ${{ env.ecr_url }}/service1:$(date +%s)
    - name: push SERVICE2 latest
      run: docker push ${{ env.ecr_url }}/service1:latest
      
